using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Sichem;

namespace StbImageResizeSharp.Generator
{
	class Program
	{
		private static void Write(Dictionary<string, string> input, StringBuilder output)
		{
			foreach (var pair in input)
			{
				output.Append(pair.Value);
			}
		}

		private static string PostProcess(string data)
		{
			data = Utility.ReplaceNativeCalls(data);

			data = data.Replace("((void*)(0))", "null");
			data = data.Replace("((void *)(0))", "null");
			data = data.Replace("default: ;", "default: throw new Exception(\"Mode \" + context->init_mode + \" is not supported.\");");
			data = data.Replace("(int)(((p->w) > (q->w))?-1:((p->w) < (q->w)))",
				"(int)(((p->w) > (q->w))?-1:((p->w) < (q->w))?1:0)");
			data = data.Replace("(int)(((p->was_packed) < (q->was_packed))?-1:((p->was_packed) > (q->was_packed)))", 
				"(int)(((p->was_packed) < (q->was_packed))?-1:((p->was_packed) > (q->was_packed))?1:0)");
			data = data.Replace("(int)(!(((rects[i].x) == (0xffff)) && ((rects[i].y) == (0xffff))))",
				"(((rects[i].x) == (0xffff)) && ((rects[i].y) == (0xffff)))?0:1");

			return data;
		}

		static void Process()
		{
			var parameters = new ConversionParameters
			{
				InputPath = @"stb_rect_pack.h",
				Defines = new string[]
				{
					"STB_RECT_PACK_IMPLEMENTATION"
				},
				SkipStructs = new string[]
				{
					"stbrp_context"
				},
				SkipGlobalVariables = new string[]
				{
				},
				SkipFunctions = new string[]
				{
				},
				Classes = new string[]
				{
				},
				GlobalArrays = new string[]
				{
				}
			};

			var cp = new ClangParser();

			var result = cp.Process(parameters);

			// Write output
			var sb = new StringBuilder();
			sb.AppendLine(string.Format("// Generated by Sichem at {0}", DateTime.Now));
			sb.AppendLine();

			sb.AppendLine("using System;");
			sb.AppendLine("using System.Runtime.InteropServices;");

			sb.AppendLine();

			sb.Append("namespace StbRectPackSharp\n{\n\t");
			sb.AppendLine("unsafe partial class StbRectPack\n\t{");

			Write(result.Constants, sb);
			Write(result.GlobalVariables, sb);
			Write(result.Enums, sb);
			Write(result.Structs, sb);
			Write(result.Methods, sb);

			sb.Append("}\n}");
			var data = sb.ToString();

			// Post processing
			Logger.Info("Post processing...");
			data = PostProcess(data);

			File.WriteAllText(@"..\..\..\..\..\src\StbRectPack.Generated.cs", data);
		}

		static void Main(string[] args)
		{
			try
			{
				Process();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.Message);
				Console.WriteLine(ex.StackTrace);
			}

			Console.WriteLine("Finished. Press any key to quit.");
			Console.ReadKey();
		}
	}
}